### ISSUE TITLE
Possible Citation for a Related Survey

### ISSUE THREAD

**Issue by MinliangLin** [jianzongwu/Awesome-Open-Vocabulary#21]
In my opinion, the survey found at https://arxiv.org/pdf/2307.09220.pdf appears to closely align with the subject matter of your work and might contribute valuable context or insights to your readers 😁

**Comment by lxtGH** [comment]
@MinliangLin Hi! Clearly, our work is the first and appears on arXiv in 06-23. In addition, the motivation and scope are different for these two surveys.
