### ISSUE TITLE
Adding paper

### ISSUE THREAD

**Issue by Z-MU-Z** [jianzongwu/Awesome-Open-Vocabulary#22]
Hello! Thanks for your great work! Please consider adding the following paper: SegPrompt(ICCV2023) https://arxiv.org/pdf/2308.06531.pdf in Class-agnostic Segmentation.

**Comment by lxtGH** [comment]
Hi! @Z-MU-Z Please send us a PR. We will merge it.

**Comment by lihengtao** [comment]
Hi! Please review our PR. #24
